# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Synthesizer DIY with Mich theme"
license = "MIT"
licenselink = "https://github.com/michd/synth.michd.me-theme/blob/master/LICENSE.md"
description = ""
homepage = "https://synth.michd.me/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Michael Duerinckx"
  homepage = "http://michd.me"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
